CREATE TABLE CARRERA (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    CODIGOCARRERA CHAR(2),
    NOMBRE VARCHAR(20) NOT NULL,
    CONSTRAINT ID_CARRERA_PK PRIMARY KEY (ID)
);

CREATE TABLE CORREDORES (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, -- Id autonumérico
    NOMBRE VARCHAR(20) NOT NULL,
    APELLIDOS VARCHAR(40) NOT NULL,
    TELEFONO VARCHAR(15),
    EMAIL VARCHAR(30),
    CARRERA INTEGER NOT NULL,
    FECHA_NACIMIENTO DATE,
    NUM_HIJOS SMALLINT,
    ESTADO_CIVIL CHAR(1),
    JUBILADO BOOLEAN,
    FOTO VARCHAR(30),
    CONSTRAINT ID_CORREDORES_PK PRIMARY KEY (ID),
    CONSTRAINT CARR_CORREDORES_FK FOREIGN KEY (CARRERA) REFERENCES CARRERA (ID)
);

